server:  
  port: ${PORT:8765}
  contextPath: /web-app

spring:  
  application:
    name: gateway-server
  datasource:
    url: jdbc:mysql://localhost:3306/oath2?useSSL=false
    username: root
    password: root
  #aop:
    #proxy-target-class: true
    

    
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG    
    org.springframework.cloud.netflix.zuul: TRACE
    org.springframework.security: DEBUG
      
zuul:
  routes:  
    auth:
      path: /auth/**
      sensitiveHeaders:
      url: http://localhost:9999/auth/
      serviceId: auth-server
    account:
      path: /account/**
      sensitiveHeaders:
      serviceId: account-service
    customer:
      path: /customer/**
      sensitiveHeaders:
      #url: http://localhost:8083/
      serviceId: customer-service
  #add-proxy-headers: true      
            
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



security:
  #basic:
    #enabled: false
  user:
    #name: root
    password: none  
  oauth2:
    #sso:
      #loginPath: /uaa/login   
    client:
      client-id: customer-service
      #client-secret: secret
      accessTokenUri: http://localhost:9999/auth/oauth/token
      userAuthorizationUri: http://localhost:9999/auth/oauth/authorize      
      preEstablishedRedirectUri: http://localhost:8765/web-app/login
      registeredRedirectUri: http://localhost:8765/web-app/login
      useCurrentUri: false
      #clientAuthenticationScheme: form
    resource:
      #userInfoUri: http://localhost:8765/uaa/user
      #preferTokenInfo: false  
      jwt:
        #keyUri: http://localhost:9999/uaa/oauth/token_key
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
          -----END PUBLIC KEY-----
      #token-info-uri: http://localhost:9999/oauth/check_token 
      #userInfoUri: http://localhost:9999/uaa/user
      #preferTokenInfo: false  
      #authenticationScheme: form
  sessions: ALWAYS  

#proxy:
  #auth:
    #routes:
      #customer: oauth2
      #account: oauth2
          
#security:
#  oauth2:
#    sso:
#      loginPath: /uaa/login      
#    client:
#      accessTokenUri: http://localhost:8765/uua/oauth/token
#      userAuthorizationUri: http://localhost:8765/uua/oauth/authorize
#      clientId: acme
#      clientSecret: secret
#      clientAuthenticationScheme: form   
#    resource:
#      userInfoUri: http://localhost:9999/user
#      preferTokenInfo: false  
#  sessions: ALWAYS 