server:  
  port: ${PORT:8083}

spring:  
  application:
    name: customer-service
    
eureka:  
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1000
    leaseExpirationDurationInSeconds: 2000
          
logging:
  level:
    org.springframework.security: TRACE
    
security:
  sessions : stateless
  user:
    password: none
  oauth2:
    client:
      client-id: account-service
      client-secret: secret
      scope: read
      access-token-uri: http://localhost:9999/auth/oauth/access_token
      user-authorization-uri: http://localhost:9999/auth/oauth/authorize
    resource:
      #token-info-uri: http://localhost:9999/oauth/check_token  
      jwt:
        #keyUri: http://localhost:9999/uaa/oauth/token_key
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
          -----END PUBLIC KEY-----          