server:  
  port: ${PORT:8083}

spring:  
  application:
    name: customer-service
    
eureka:  
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1000
    leaseExpirationDurationInSeconds: 2000
          
    
security:
  user:
    password: none
  oauth2:
    client:
      client-id: customer-service
      client-secret: secret
      scope: read
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
    resource:
      token-info-uri: http://localhost:9999/oauth/check_token    