server:  
  port: ${PORT:9999}

spring:  
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:/script/schema.sql
    data: classpath:/script/data.sql
    
logging:
  level:
    org.springframework.security: TRACE
      
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/